CREATE DATABASE mybatis;

CREATE TABLE IF NOT EXISTS t_user(
  user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_name VARCHAR(40) NOT NULL ,
  password VARCHAR(40) NOT NULL ,
  mobile VARCHAR(20) NOT NULL,
  email VARCHAR(20)
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

ALTER TABLE t_user ADD COLUMN isdelete int(1) DEFAULT 0;
ALTER TABLE t_user DROP COLUMN password;