server:
  port: 8080

spring:
    datasource:
        name: test      #数据源名称
        url: jdbc:mysql://127.0.0.1:3306/mybatis?characterEncoding=utf8&useSSL=false
        username: root
        password: hwbmysql
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        # 配置监控统计拦截的filters
        filters: stat
        # 初始化数据库连接池最大激活数,初始化大小，最小空闲数
        maxActive: 20
        initialSize: 1
        minIdle: 1
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        #validationQuery是用来验证数据库连接的查询语句，mysql固定为select 1
        validationQuery: select 1
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.funcodeh.mybatis.springbootmybatisdemo

#pagehelper分页插件
pagehelper:
    #分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。可以配置helperDialect属性来指定分页插件使用哪种方言
    helperDialect: mysql
    #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页
    reasonable: true
    #支持通过 Mapper 接口参数来传递分页参数，默认值false，
    #分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
    supportMethodsArguments: true
    #计算sql数
    params: count=countSql