CREATE DATABASE shiro;

CREATE TABLE IF NOT EXISTS user(
  user_id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  user_name VARCHAR(40) NOT NULL ,
  password VARCHAR(40) NOT NULL ,
  isdelete int(1) DEFAULT '0',
  createTime TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间'
) ENGINE=INNODB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;

ALTER TABLE user ADD COLUMN salt varchar(20) not null after password;

CREATE TABLE IF NOT EXISTS role(
  id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键id',
  code VARCHAR(25) NULL DEFAULT NULL COMMENT '角色代码',
  name VARCHAR(25) NOT NULL DEFAULT '1' COMMENT '角色名称',
  isDeleted BIT(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  createTime TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`)
)ENGINE = InnoDB DEFAULT CHARACTER SET = utf8  COMMENT = '角色表';


CREATE TABLE IF NOT EXISTS permission (
   id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '权限id',
   code VARCHAR(25) NOT NULL COMMENT '权限编码',
   name VARCHAR(25) NULL DEFAULT NULL COMMENT '权限名称',
   PRIMARY KEY (`id`)
)ENGINE = InnoDB DEFAULT CHARACTER SET = utf8   COMMENT = '权限表';

CREATE TABLE IF NOT EXISTS user_role (
   id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键id',
   user_id VARCHAR(10) NOT NULL COMMENT '用户id',
   role_id VARCHAR(10) NULL DEFAULT NULL COMMENT '角色id',
   PRIMARY KEY (`id`)
)ENGINE = InnoDB DEFAULT CHARACTER SET = utf8   COMMENT = '用户角色关系表';

CREATE TABLE IF NOT EXISTS role_permission (
   id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键id',
   role_id VARCHAR(10) NOT NULL COMMENT '角色id',
   permission_id VARCHAR(10) NULL DEFAULT NULL COMMENT '权限id',
   PRIMARY KEY (`id`)
)ENGINE = InnoDB DEFAULT CHARACTER SET = utf8   COMMENT = '角色权限关系表';